
//Employee action type
export const EMPLOYEE_GET_REQUEST = 'EMPLOYEE_GET_REQUEST';
export const EMPLOYEE_GET_SUCCESS = 'EMPLOYEE_GET_SUCCESS';
export const EMPLOYEE_ADD_REQUEST = 'EMPLOYEE_ADD_REQUEST';
export const EMPLOYEE_ADD_SUCCESS = 'EMPLOYEE_ADD_SUCCESS';
export const EMPLOYEE_DELETE_REQUEST = 'EMPLOYEE_DELETE_REQUEST';
export const EMPLOYEE_DELETE_SUCCESS = 'EMPLOYEE_DELETE_SUCCESS';
export const EMPLOYEE_UPDATE_REQUEST = 'EMPLOYEE_UPDATE_REQUEST';
export const EMPLOYEE_UPDATE_SUCCESS = 'EMPLOYEE_UPDATE_SUCCESS';
export const EMPLOYEE_SELECTED_REQUEST = 'EMPLOYEE_SELECTED_REQUEST';
export const EMPLOYEE_SELECTED_SUCCESS = 'EMPLOYEE_SELECTED_SUCCESS';
export const EMPLOYEE_ACTION_FAIL = 'EMPLOYEE_ACTION_FAIL';

